server:
  port: 20100

spring:
  application:
    name: daxpay-channel-one
  datasource:
    url: jdbc:postgresql://localhost:5432/daxpay_channel
    username: daxpay
    password: daxpay
    driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: UTC
