<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cn.daxpay.open.channel.one</groupId>
        <artifactId>daxpay-channel-one</artifactId>
        <version>4.0.0-beta3</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>daxpay-platform</artifactId>
    <packaging>pom</packaging>
    <description>通道适配基础层(对标主项目 daxpay-platform)</description>

    <modules>
        <module>daxpay-platform-core</module>
        <module>daxpay-platform-common</module>
        <module>daxpay-platform-service</module>
    </modules>
</project>
